FORMAT: 1A
HOST: http://0.0.0.0

# senao-sc

HTTP APIs for Account and Password Management

## API 1 [/users]

### Find all users [GET]
`/users`
+ Response 200 (application/json)
    + Body
            [
                {
                    "u_id": "a5f5b8b8-458e-42bb-af73-65e11cb321d1",
                    "account": "sandy",
                    "password": "Sandy123"
                }
            ]

### Find one user [GET/users/a5f5b8b8-458e-42bb-af73-65e11cb321d1]
`/users/{id}`
+ Response 200 (application/json)

    + Body
            {
                "Success": true
            }

### Create a user [POST]
`/users/{id}`
+ Request (application/json)

        {
            "account": "amber",
            "password": "Amber123"
        }

+ Response 201 (application/json)

    + Body

            {
                "Success": true
            }
            

### Modify a user [PUT/users/a5f5b8b8-458e-42bb-af73-65e11cb321d1]
`/users/{id}`
+ Request (application/json)

        {
            "account": "sandy_new",
            "password": "Sandy123_new"
        }

+ Response 204 (application/json)

### Delete a user [DELETE/users/a5f5b8b8-458e-42bb-af73-65e11cb321d1]
`/users/{id}`
+ Response 200 (application/json)
    
    + Body
            {
                "Success": true
            }


## API 2 [/auth]
### Verify the user [POST]
`/auth`
+ Request (application/json)

        {
            "account": "sandy",
            "password": "Sandy123"
        }

+ Response 200 (application/json)

    + Body

            {
                "Success": true
            }